name: Node.js CI

on:
  push:
    branches:
      - main  # Set the branch you want to trigger on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest  # Use the appropriate PostgreSQL version
        env:
          POSTGRES_DB: postgres         # Name of the test database
          POSTGRES_USER: postgres        # Your database username
          POSTGRES_PASSWORD: postgres # Your database password
        ports:
          - 5432:5432
        options: >
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 

    steps:
    - name: Debug Environment Variables
      run: |
        echo "API_USERNAME available: ${API_USERNAME:+yes}"
        echo "API_PASSWORD available: ${API_PASSWORD:+yes}"
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '24.13.0'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        cd server  # Navigate to your Node.js server folder
        npm install

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do 
          PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres -d postgres -c "SELECT 1;" && break || sleep 5; 
        done        

    - name: Run tests
      env:
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
        API_USERNAME: ${{ secrets.API_USERNAME }}
      run: |
        cd server  # Navigate to your Node.js server folderx
        npm run build
        cp -R src/tests/*.sql dist/tests/
        cd dist
        NODE_ENV=test DB_HOST=127.0.0.1 DB_USER=postgres DB_PWD=postgres DB_PORT=5432 DB_NAME=postgres node tests/test-database-init.js
        NODE_ENV=test DB_HOST=127.0.0.1 DB_USER=postgres DB_PWD=postgres DB_PORT=5432 DB_NAME=postgres npx mocha --exit  tests/**/*.test.js

    - name: Build application
      run: |
        cd server  # Navigate to your Node.js server folder
        npm run build  # If you have a build step
