name: Node.js CI

on:
  push:
    branches:
      - main  # Set the branch you want to trigger on
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing

    services:
      db:
        image: postgres:latest  # Use the appropriate PostgreSQL version
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PWD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}        
        ports:
          - 5432:5432
        options: >
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 

    steps:  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '24.13.0'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        cd server  # Navigate to your Node.js server folder
        npm install   

    - name: Run tests
      env:
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
        API_USERNAME: ${{ secrets.API_USERNAME }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_TOKEN_EXP: ${{ secrets.JWT_TOKEN_EXP }}
        NODE_ENV: test
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PWD: ${{ secrets.DB_PWD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        cd server  # Navigate to your Node.js server folderx
        npm run build
        cp -R src/tests/*.sql dist/tests/
        cd dist
        node tests/test-database-init.js
        npx mocha --exit  tests/**/*.test.js

    - name: Build application
      run: |
        cd server  # Navigate to your Node.js server folder
        npm run build  # If you have a build step
